name: Docker

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: reedom/openapi2aspida


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Checkout repository
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASS: ${{secrets.DOCKER_PASS}}
        run:
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: Build the Docker image
        run: docker build . --tag $IMAGE_NAME:$(date +%s)

      - name: Build the Docker image
        run: docker build . --tag $IMAGE_NAME:latest

      - name: Docker push
        run: docker push -a $IMAGE_NAME
